# Generated by Django 6.0.7 on 2026-07-31 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('creative_type', models.CharField(choices=[('actor', 'Actor'), ('director', 'Director'), ('musician', 'Musician'), ('photographer', 'Photographer'), ('writer', 'Writer'), ('editor', 'Editor'), ('designer', 'Designer'), ('other', 'Other')], max_length=30)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('experienced', 'Experienced'), ('professional', 'Professional')], max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(max_length=120)),
                ('portfolio_url', models.URLField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('available_for_projects', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creative_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
